before:
  hooks:
    - go mod download

builds:
  - binary: cloudwatch-export
    id: "cloudwatch-export"
    main: main.go
    goos:
      - linux
    goarch:
      - amd64

snapshot:
  name_template: "{{ .Tag }}"

archives:
  - format: zip
    files:
      - LICENSE
